#
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
package: "magritte"
type: "TrackingSubgraphCpu"

# A graph that performs motion tracking on detections. It's a wrapper around the
# MediaPipe object tracking subgraph.
#
# The input streams don't need to have the same timestamps. The detections
# stream can be at a lower rate (e.g., obtained from a video that was
# downsampled to a lower framerate). The output detection stream will be
# generated for the same timestamps as the input video packets.
#
# Inputs:
# - input_video: The ImageFrame stream in which objects should be tracked. Its
#   motion will be analyzed for the tracking.
# - detections: The detections to be tracked.
#
# Outputs:
# - tracked_detections: Resulting tracked detections.

input_stream: "IMAGE:input_video"
input_stream: "DETECTIONS:detections"
output_stream: "DETECTIONS:tracked_detections"

node {
  calculator: "ObjectTrackingSubgraphCpu"
  input_stream: "VIDEO:input_video"
  input_stream: "DETECTIONS:detections"
  output_stream: "DETECTIONS:tracked_detections"
}
