#
# Copyright 2020-2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This is a compatibility option with tracked detections as they don't have
# keypoints anymore. Can also be used with future non-face detections.
package: "magritte"
type: "DetectionToRenderDataSubgraph"

input_stream: "SIZE:image_size"
input_stream: "DETECTIONS:output_detections"
output_stream: "RENDER_DATA:render_data"

# Converts results of face detection into a rectangle (normalized by image size)
# that encloses the face.
node {
  calculator: "DetectionsToRectsCalculator"
  input_stream: "DETECTIONS:output_detections"
  input_stream: "IMAGE_SIZE:image_size"
  output_stream: "NORM_RECTS:face_rect"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionsToRectsCalculatorOptions] {
      output_zero_rect_for_empty_detections: true
    }
  }
}

# Expands and shifts the rectangle that contains the face so that it's likely
# to cover the entire face.
node {
  calculator: "RectTransformationCalculator"
  input_stream: "NORM_RECTS:face_rect"
  input_stream: "IMAGE_SIZE:image_size"
  output_stream: "output_rects"
  node_options: {
    [type.googleapis.com/mediapipe.RectTransformationCalculatorOptions] {
      scale_x: 2.0
      scale_y: 2.0
      square_long: true
    }
  }
}

# Converts normalized rects to drawing primitives for annotation overlay.
node {
  calculator: "RectToRenderDataCalculator"
  input_stream: "NORM_RECTS:output_rects"
  output_stream: "RENDER_DATA:render_data"
  node_options: {
    [type.googleapis.com/mediapipe.RectToRenderDataCalculatorOptions] {
      filled: true
      color { r: 0 g: 0 b: 0 }
      thickness: 4.0
      oval: true
    }
  }
}
