#
# Copyright 2020-2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
package: "magritte"
type: "MaskPixelizationSubgraphGpu"

# Subgraph to pixelize a certain area of an image. The mask specifies which area
# is to be pixelized: the parts where the mask is black will contain the
# original image, the parts where the mask is white will contain the pixelized
# image, and for values in-between blending will be used.
#
# Inputs:
# - IMAGE: A GpuBuffer containing the image to be pixelized.
# - MASK: A GpuBuffer containing a mask. The image format of the mask doesn't
#   matter, we always use the first channel as the alpha value for blending. It
#   doesn't need to have the same resolution as the input image, if it has a
#   different resolution it will be scaled using linear interpolation (in most
#   cases, see SetStandardTextureParams in MediaPipe's GlContext class for
#   details).
#
# Outputs:
# - IMAGE: A GpuBuffer containing the resulting image.
input_stream: "IMAGE:input_video"
input_stream: "MASK:mask"
output_stream: "IMAGE:output_video"

node {
  calculator: "PixelizationCalculatorGpu"
  input_stream: "IMAGE_GPU:input_video"
  input_stream: "MASK:mask"
  output_stream: "IMAGE_GPU:output_video"
  node_options: {
    [type.googleapis.com/magritte.PixelizationCalculatorOptions] {
      # 576 has round division in 16:9 ratio to 32x18, resulting into integer
      # division when computing square pixels. Any positive float is valid.
      total_nb_pixels: 576
      # ignore_mask: true # Debug option to apply to whole picture
    }
  }
}
